apiVersion: v1
kind: Pod
metadata:
  name: homework01-pod
  namespace: homework
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 8000
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
    lifecycle:
      preStop:
        exec:
          command: ["sh", "-c", "rm /usr/share/nginx/html/index.html"]
  initContainers:
  - name: init
    image: busybox:latest
    command: ["sh", "-c", "echo '<html><body><h1>Тест</h1></body></html>' > /init/index.ntml"]
    volumeMounts:
      - name: html
        mountPath: /init
  volumes:
    - name: html
      emptyDir: {}